name: Windows-10
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Launching Windows
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Invoke-WebRequest -Uri "https://github.com" -OutFile "ngrok.exe"
        .\ngrok.exe authtoken 3JWvJ1hXLYaW006LCkBUiou10jA_7UENrG1qGH3BWe2hLTpwZ3JVvJ1hXLYaW006LCkBUiou10jA_7UENrG1qGH3BWe2hLpwZ
        Start-Process .\ngrok.exe -ArgumentList "tcp 3389"
        Write-Host "Windows Server is running permanently..."
        Start-Sleep -Seconds 21600
